### ISSUE TITLE
Changing SciML from Zygote-first to Mooncake-first

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLSensitivity.jl#1279]
Cover the main solvers:

* DiffEq, done!
* NonlinearSolve, https://github.com/SciML/NonlinearSolve.jl/pull/719
* LinearSolve, https://github.com/SciML/LinearSolve.jl/pull/801
* Integrals: https://github.com/SciML/Integrals.jl/blob/409acc3a639c84cf066d448f1491c5027c15a32c/ext/IntegralsZygoteExt.jl#L5

Get all of the packages with ChainRules to make sure what is required to move to Mooncake does:

* https://github.com/SciML/DiffEqGPU.jl/blob/a802496aff598650fb30123490b0e6bec15b3533/src/algorithms.jl#L173-L179
* https://github.com/SciML/ComponentArrays.jl/blob/e6714d8d65a580b1b2bca533e562615c05dbfe81/src/compat/chainrulescore.jl#L9
* https://github.com/SciML/ModelingToolkit.jl/blob/cc3f4bd88f84ac4f4fe48758ebb9bc017b32e6fc/src/adjoints.jl#L2
* https://github.com/SciML/DataInterpolations.jl/blob/912d889c28c856802df0db93f423685604857013/ext/DataInterpolationsChainRulesCoreExt.jl#L8
* https://github.com/SciML/SciMLBase.jl/blob/b59a86d47aac4709d4605c0de96e6c41663fbf74/ext/SciMLBaseZygoteExt.jl#L6
* https://github.com/SciML/RecursiveArrayTools.jl/blob/3710526066702c8163b60b248e4ce9192fec2fa2/ext/RecursiveArrayToolsZygoteExt.jl#L6
* https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/0e75c63c866819aa7dc23a703d7c2768a52fd52e/src/Blocks/sources.jl#L2

Make sure Lux.jl is compatible enough.

Once all of those are hit, we update the docs to use Mooncake instead of Zygote everywhere.

**Comment by SebastianM-C** [comment]
Should Optimization also be on the list?

**Comment by AstitvaAggarwal** [comment]
FYI for the issue DiffEqGPU, ModelingToolkitStandardLibrary do not need special Mooncake handling and the rest parts in this issue are addressed except for the following remaining possible extension requirements ? : 

- https://github.com/SciML/SciMLBase.jl/blob/b59a86d47aac4709d4605c0de96e6c41663fbf74/ext/SciMLBaseZygoteExt.jl#L6

WIll do soon and also let me know if I'm understanding the status correctly. Thanks

**Comment by ChrisRackauckas** [comment]
The main issues remaining are:

* https://github.com/SciML/SciMLSensitivity.jl/issues/1424 (should be solved by https://github.com/SciML/SciMLBase.jl/pull/1214)
* https://github.com/SciML/SciMLSensitivity.jl/issues/1425 (seems fundamental to mooncake, but solved by moving that tutorial to enzyme)
* https://github.com/SciML/SciMLSensitivity.jl/issues/1426 (should be solved by https://github.com/SciML/ComponentArrays.jl/pull/352)
* https://github.com/SciML/SciMLSensitivity.jl/issues/1427 (should be solved by https://github.com/chalk-lab/Mooncake.jl/pull/1143)

I have to test locally for now since DI's upper bounds on Mooncake prohibit using the ComponentArrays friendly_adjoints fixes (@gdalle is aware), but I'm testing locally that these tutorials build. 

Indeed, DiffEqGPU.jl is covered by the Ensemble rules added in SciMLBase, and RecursiveArrayTools should be handled by https://github.com/SciML/RecursiveArrayTools.jl/pull/575 (+ RAT v4 moves VectorOfArray to being an AbstractArray, so that should be handled automatically and much better with the big release there).

So with the DataInterpolations PRs merged, I think we're Mooncake ready? I'm testing locally a bunch of stuff to see if I find anything but things are looking good, other than that quirk with static arrays that has to be enzyme, but that's because Mooncake wants to mutate internally so that either needs a fix in Mooncake or we just have to say Mooncake doesn't support SArrays. For now we're just doing the latter and going Enzyme there.

> Should Optimization also be on the list?

I don't think it needs to be, since it doesn't have any Mooncake rules.

**Comment by ChrisRackauckas** [comment]
I think this is sufficiently complete. SciML came out now as basically Enzyme-first, it got a lot more coverage for us. But we'd prefer Mooncake over Zygote these days, so the issue did its job. Anyways, it's Enzyme and Mooncake now, Zygote no more, and all major issues completed. There's still some missing features of Mooncake, like how it works over other ADs, that make Enzyme preferred, but those are relatively minor in the grand scheme of things and anyone using Mooncake should generally have a fine time.
